# .github/workflows/ci.yml

on:
    pull_request:
    push:
      branches: [main]
  
jobs:
    ci:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Run
          run: |
            npm install
            npm run start
  
        - name: Deploy
          # Only run this step if the branch is master
          if: github.ref == 'refs/heads/master'
          env:
            deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          run: |
            curl "$deploy_url"